language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
before_script:
  - composer self-update
  - composer install --no-interaction
script: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-text
jobs:
  allow_failures:
  - php: 7.2